version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      nuget:
        patterns:
          - "*"
    open-pull-requests-limit: 5
