name: Code Analysis

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/GodotSharpSome.Drawing2D/**"
      - "!src/**.sln"
  pull_request:
    branches: [main]
    paths:
      - "src/GodotSharpSome.Drawing2D/**"
      - "!src/**.sln"
  schedule:
    - cron: "40 14 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    uses: jirikostiha/ci/.github/workflows/code-analysis.yml@v1
    permissions:
      contents: read
      security-events: write
    with:
      language: csharp
