name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    uses: jirikostiha/ci/.github/workflows/auto-approve.yml@v1
    permissions:
      pull-requests: write
    with:
      actors: "dependabot[bot],github-actions[bot]"
