name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/GodotSharpSome.Drawing2D/**"
      - "!src/**.sln"

concurrency:
  group: ${{ github.workflow }}

jobs:
  benchmark:
    uses: jirikostiha/ci/.github/workflows/benchmark.yml@v1
    permissions:
      contents: write
      deployments: write
    with:
      project: src/quality/GodotSharpSome.Drawing2D.Benchmarks
      results-dir: benchmarks/results
      dotnet-version: "8.0.x"
