name: Build

env:
  sln-path: "./src/godot sharp some.sln"

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '!src/**.sln' # ignore sln changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: .NET Info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore "${{ env.sln-path }}"

      - name: Build debug
        run: dotnet build "${{ env.sln-path }}" -c Debug --no-restore

      - name: Test
        run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Tests ${{ matrix.dotnet-version }}
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
