name: Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: "Build configuration"
        type: choice
        options: [Debug, Release]
        default: Debug
  push:
    paths:
      - "src/**"
      - "!src/**.sln"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.configuration || 'Debug' }}
  cancel-in-progress: true

jobs:
  build:
    uses: jirikostiha/ci/.github/workflows/dotnet-build.yml@v1
    permissions:
      contents: read
      checks: write
    with:
      solution: "./src/godot sharp some.sln"
      configuration: ${{ inputs.configuration || 'Debug' }}
      dotnet-version: "8.0.x"
