name: History Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  cleanup:
    uses: jirikostiha/ci/.github/workflows/clean-history.yml@v1
    permissions:
      actions: write
