name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    uses: jirikostiha/ci/.github/workflows/docs.yml@v1
    permissions:
      contents: read
      pages: write
      id-token: write
