name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

jobs:
  build:
    uses: jirikostiha/ci/.github/workflows/dotnet-build.yml@v1
    permissions:
      contents: read
      checks: write
    with:
      solution: "./src/godot sharp some.sln"
      configuration: Release
      ref: ${{ inputs.tag || github.ref_name }}
      artifacts: true
      binaries-path: artf/GodotSharpSome.Drawing2D/bin
      dotnet-version: "8.0.x"

  benchmark:
    needs: build
    uses: jirikostiha/ci/.github/workflows/benchmark.yml@v1
    permissions:
      contents: write
      deployments: write
    with:
      project: src/quality/GodotSharpSome.Drawing2D.Benchmarks
      dotnet-version: "8.0.x"

  docs:
    needs: [build, benchmark]
    uses: jirikostiha/ci/.github/workflows/docs.yml@v1
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      version: ${{ inputs.tag || github.ref_name }}

  release:
    needs: build
    uses: jirikostiha/ci/.github/workflows/github-release.yml@v1
    permissions:
      contents: write
    with:
      tag: ${{ inputs.tag || github.ref_name }}

  publish:
    needs: build
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/nuget-publish.yml

  asset-library:
    needs: publish
    uses: jirikostiha/ci/.github/workflows/godot-publish.yml@v1
    with:
      username: jiri
      asset-id: "7436"
      asset-template: .github/asset-template.json.hb
      ref: ${{ inputs.tag || github.ref_name }}
    secrets:
      password: ${{ secrets.GODOT_ASSET_STORE_PASSWORD }}
