name: Commit Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint:
    uses: jirikostiha/ci/.github/workflows/lint-commit.yml@v1
    permissions:
      contents: read
      pull-requests: read
    with:
      config: .github/commitlint_config.mjs
