name: Code Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: jirikostiha/ci/.github/workflows/lint-code.yml@v1
    permissions:
      contents: write
    with:
      dir: src
