name: Configuration Lint

on:
  workflow_dispatch:
  workflow_call: # release gate
    inputs:
      ref:
        type: string
        default: ""
  pull_request:
    branches: ["release/**"]
    paths:
      - "**.yml"

jobs:
  run-linters:
    name: Config linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - name: Lint yaml
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: ".github/yamllint.yml"
