name: Code Lint

on:
  workflow_dispatch:
  workflow_call: # release gate
    inputs:
      check-only:
        type: boolean
        default: false
      ref:
        type: string
        default: ""
  pull_request:
    branches: ["release/**"]
    paths:
      - "**.cs"

concurrency:
  group: ${{ github.workflow }}-lint-code-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: jirikostiha/ci/.github/workflows/lint-code.yml@v1
    permissions:
      contents: write
      checks: write
    with:
      check-only: ${{ inputs.check-only || false }}
      ref: ${{ inputs.ref }}
      dir: src
