name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: jirikostiha/ci/.github/workflows/dotnet-build.yml@v1
    permissions:
      contents: read
      checks: write
    with:
      solution: "./src/godot sharp some.sln"
      configuration: Release
      ref: ${{ inputs.tag || github.ref_name }}
      artifacts: true
      binaries-path: src/GodotSharpSome.Drawing2D/bin

  release:
    needs: build
    uses: jirikostiha/ci/.github/workflows/gh-release.yml@v1
    permissions:
      contents: write
    with:
      tag: ${{ inputs.tag || github.ref_name }}
